### ISSUE TITLE
inline + display math

### ISSUE THREAD

**Issue by nschloe** [smallstepman/org-file-readme#1]
Please add an inline and display math block.

**Comment by smallstepman** [comment]
I updated the readme with requested examples
https://github.com/smallstepman/org-file-readme/commit/b199ec78ee31c4c4f5997f5a263d62b2e2b02739#diff-ecbc1aa90e9ff97a00b0b2aab1551bceee0c4d21993146bdcb1af4de31c9cac6

**Comment by nschloe** [comment]
The language spec for math environments should be `math`. Also, the inline math elements should be inside "inline code" environments. (Simple tick in markdown, not sure what the .org syntax is.)
